import type { Metadata } from "next";
import { Archivo, Comfortaa } from "next/font/google";
import "./globals.scss";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quality | Engenharia e Consultoria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${archivo.variable} ${comfortaa.variable}`}>
      <body>{children}</body>
    </html>
  );
}
